"""OwnerLens package.

Exposes the SEC identity and raw Company Facts retrieval slice and a minimal
console entry point used to validate it.
"""

from __future__ import annotations

from owner_lens._annual import AnnualObservation
from owner_lens.balance_sheet import (
    normalize_cash,
    normalize_current_debt,
    normalize_long_term_debt,
    normalize_short_term_investments,
    normalize_total_assets,
    normalize_total_equity,
)
from owner_lens.capital_allocation import (
    DEFAULT_CAPITAL_ALLOCATION_THRESHOLDS,
    BuybackEffectiveness,
    CapitalAllocationClassification,
    CapitalAllocationDriver,
    CapitalAllocationRow,
    CapitalAllocationThresholds,
    build_capital_allocation_rows,
    capital_allocation_from_facts,
    capital_allocation_summary,
    classify_buyback_effectiveness,
    format_capital_allocation_view,
)
from owner_lens.capital_efficiency import (
    CapitalEfficiencyRow,
    capital_efficiency_from_facts,
    compute_capital_efficiency,
)
from owner_lens.compounding import (
    DEFAULT_COMPOUNDING_THRESHOLDS,
    CompoundingClassification,
    CompoundingDriver,
    CompoundingThresholds,
    EconomicCompoundingView,
    build_compounding_view,
    cagr,
    classify_compounding,
    compounding_view_from_facts,
    compounding_views_from_facts,
    format_compounding_view,
)
from owner_lens.config import (
    OwnerLensSettings,
    build_local_store,
    load_settings,
)
from owner_lens.coverage import (
    CompanyCoverage,
    LayerCoverage,
    LayerResult,
    MetricCoverage,
    company_coverage,
    company_output,
    format_coverage_report,
)
from owner_lens.economic_summary import (
    DEFAULT_ECONOMIC_SUMMARY_THRESHOLDS,
    EconomicSummaryThresholds,
    EconomicValueSummary,
    OverallEconomicValueClassification,
    SummaryDriver,
    economic_value_summary_from_facts,
    format_economic_value_summary,
    synthesize_economic_value_summary,
)
from owner_lens.economic_value import (
    DEFAULT_THRESHOLDS,
    EconomicValueClassification,
    EconomicValueDriver,
    EconomicValueSnapshot,
    EconomicValueThresholds,
    build_economic_value_snapshots,
    classify_economic_value,
    economic_value_from_facts,
    format_economic_value_view,
)
from owner_lens.ingestion import (
    FailureClass,
    IngestionFailure,
    IngestionItem,
    IngestionResult,
    IngestionStatus,
    ProcessingStatus,
    ingest_company,
)
from owner_lens.margin import (
    AnnualMetricRow,
    OperatingMargin,
    align_annual_metrics,
    operating_margins,
)
from owner_lens.metrics import (
    CanonicalMetricDefinition,
    MetricKind,
    resolve_concepts,
)
from owner_lens.operating_income import (
    AmbiguousOperatingIncomeError,
    AnnualOperatingIncomeObservation,
    AnnualOperatingIncomeSeries,
    OperatingIncomeConceptNotFoundError,
    OperatingIncomeNormalizationError,
    normalize_annual_operating_income,
)
from owner_lens.owner_economics import (
    OwnerEconomicsRow,
    compute_owner_economics,
    owner_economics_from_facts,
)
from owner_lens.persistence import (
    AnalysisDriverRecord,
    AnalysisResultRecord,
    CompanyRecord,
    CoverageResultRecord,
    DerivedMetricRecord,
    FilesystemRawSnapshotStore,
    OwnerLensStore,
    PersistenceError,
    RawSnapshotStore,
    ReportedFactRecord,
    SchemaVersionError,
    SourceSnapshotRecord,
    SqliteStore,
    StorageConnectionError,
    StorageReadError,
    StorageWriteError,
    analysis_result_records,
    company_record,
    compute_content_hash,
    coverage_result_records,
    derived_metric_records,
    reported_fact_records,
)
from owner_lens.reported import (
    AmbiguousValueError,
    AnnualSeries,
    ConceptNotFoundError,
    normalize_annual_metric,
    normalize_capital_expenditures,
    normalize_diluted_shares,
    normalize_dividends_paid,
    normalize_income_tax_expense,
    normalize_net_income,
    normalize_operating_cash_flow,
    normalize_pretax_income,
    normalize_repurchases,
    normalize_stock_based_compensation,
)
from owner_lens.revenue import (
    AmbiguousRevenueError,
    AnnualRevenueObservation,
    AnnualRevenueSeries,
    MalformedFactsError,
    RevenueConceptNotFoundError,
    RevenueNormalizationError,
    normalize_annual_revenue,
)
from owner_lens.sec import (
    CompanyFactsResult,
    CompanyIdentity,
    CompanyIdentityMismatchError,
    CompanyResolutionError,
    MalformedSecResponseError,
    MalformedTickerError,
    SecClient,
    SecError,
    SecResponseError,
    SecTransportError,
)

__all__ = [
    "DEFAULT_CAPITAL_ALLOCATION_THRESHOLDS",
    "DEFAULT_COMPOUNDING_THRESHOLDS",
    "DEFAULT_ECONOMIC_SUMMARY_THRESHOLDS",
    "DEFAULT_THRESHOLDS",
    "AmbiguousOperatingIncomeError",
    "AmbiguousRevenueError",
    "AmbiguousValueError",
    "AnalysisDriverRecord",
    "AnalysisResultRecord",
    "AnnualMetricRow",
    "AnnualObservation",
    "AnnualOperatingIncomeObservation",
    "AnnualOperatingIncomeSeries",
    "AnnualRevenueObservation",
    "AnnualRevenueSeries",
    "AnnualSeries",
    "BuybackEffectiveness",
    "CanonicalMetricDefinition",
    "CapitalAllocationClassification",
    "CapitalAllocationDriver",
    "CapitalAllocationRow",
    "CapitalAllocationThresholds",
    "CapitalEfficiencyRow",
    "CompanyCoverage",
    "CompanyFactsResult",
    "CompanyIdentity",
    "CompanyIdentityMismatchError",
    "CompanyRecord",
    "CompanyResolutionError",
    "CompoundingClassification",
    "CompoundingDriver",
    "CompoundingThresholds",
    "ConceptNotFoundError",
    "CoverageResultRecord",
    "DerivedMetricRecord",
    "EconomicCompoundingView",
    "EconomicSummaryThresholds",
    "EconomicValueClassification",
    "EconomicValueDriver",
    "EconomicValueSnapshot",
    "EconomicValueSummary",
    "EconomicValueThresholds",
    "FailureClass",
    "FilesystemRawSnapshotStore",
    "IngestionFailure",
    "IngestionItem",
    "IngestionResult",
    "IngestionStatus",
    "LayerCoverage",
    "LayerResult",
    "MalformedFactsError",
    "MalformedSecResponseError",
    "MalformedTickerError",
    "MetricCoverage",
    "MetricKind",
    "OperatingIncomeConceptNotFoundError",
    "OperatingIncomeNormalizationError",
    "OperatingMargin",
    "OverallEconomicValueClassification",
    "OwnerEconomicsRow",
    "OwnerLensSettings",
    "OwnerLensStore",
    "PersistenceError",
    "ProcessingStatus",
    "RawSnapshotStore",
    "ReportedFactRecord",
    "RevenueConceptNotFoundError",
    "RevenueNormalizationError",
    "SchemaVersionError",
    "SecClient",
    "SecError",
    "SecResponseError",
    "SecTransportError",
    "SourceSnapshotRecord",
    "SqliteStore",
    "StorageConnectionError",
    "StorageReadError",
    "StorageWriteError",
    "SummaryDriver",
    "align_annual_metrics",
    "analysis_result_records",
    "build_capital_allocation_rows",
    "build_compounding_view",
    "build_economic_value_snapshots",
    "build_local_store",
    "cagr",
    "capital_allocation_from_facts",
    "capital_allocation_summary",
    "capital_efficiency_from_facts",
    "classify_buyback_effectiveness",
    "classify_compounding",
    "classify_economic_value",
    "company_coverage",
    "company_output",
    "company_record",
    "compounding_view_from_facts",
    "compounding_views_from_facts",
    "compute_capital_efficiency",
    "compute_content_hash",
    "compute_owner_economics",
    "coverage_result_records",
    "derived_metric_records",
    "economic_value_from_facts",
    "economic_value_summary_from_facts",
    "format_capital_allocation_view",
    "format_compounding_view",
    "format_coverage_report",
    "format_economic_value_summary",
    "format_economic_value_view",
    "ingest_company",
    "load_settings",
    "main",
    "normalize_annual_metric",
    "normalize_annual_operating_income",
    "normalize_annual_revenue",
    "normalize_capital_expenditures",
    "normalize_cash",
    "normalize_current_debt",
    "normalize_diluted_shares",
    "normalize_dividends_paid",
    "normalize_income_tax_expense",
    "normalize_long_term_debt",
    "normalize_net_income",
    "normalize_operating_cash_flow",
    "normalize_pretax_income",
    "normalize_repurchases",
    "normalize_short_term_investments",
    "normalize_stock_based_compensation",
    "normalize_total_assets",
    "normalize_total_equity",
    "operating_margins",
    "owner_economics_from_facts",
    "reported_fact_records",
    "resolve_concepts",
    "synthesize_economic_value_summary",
]


def main() -> None:
    """Console entry point; delegates to the CLI dispatcher."""
    from owner_lens.cli import main as cli_main

    raise SystemExit(cli_main())


# $env:OWNER_LENS_SEC_USER_AGENT = "OwnerLens admin@example.com"
# uv run owner-lens ingest ADBE
# uv run owner-lens ingest V
# uv run owner-lens ingest COST
